#baseURL = 'https://datadiego.github.io/blog/'
locale = 'es-ES'
title = '/dev/random'
theme = 'risotto'
author = 'datadiego'
copyright = '© datadiego'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[pagination]
pagerSize = 5

[params.theme]
palette = "base16-dark"

[params.about]
title = "/dev/random"
description = "Cultura hacker, software open source y arte hiperdigital"
logo = "✨"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/datadiego"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "juandiegomariscal@gmail.com"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = false
    codeFences = true

[params]
  mermaid = true
  noindex = false

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true
